DROP TABLE IF EXISTS item;
DROP TABLE IF EXISTS drawer;
DROP TABLE IF EXISTS shelf;

DROP TABLE IF EXISTS ITEM;
DROP TABLE IF EXISTS DRAWER;
DROP TABLE IF EXISTS SHELF;
DROP TABLE IF EXISTS REL_USER_LIST;
DROP TABLE IF EXISTS SHELF_LIST;
DROP TABLE IF EXISTS END_USER;
DROP TABLE IF EXISTS USER_ROLE;

CREATE TABLE IF NOT EXISTS END_USER
(
    ID        INT          NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS SHELF_LIST (
    ID INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS REL_USER_LIST (
    USER_ID INT NOT NULL,
    LIST_ID INT NOT NULL,
    PRIMARY KEY (USER_ID, LIST_ID),
    CONSTRAINT FK_USER_ID FOREIGN KEY (USER_ID) REFERENCES END_USER(ID),
    CONSTRAINT FK_LIST_ID FOREIGN KEY (LIST_ID) REFERENCES SHELF_LIST(ID)
);

CREATE TABLE IF NOT EXISTS SHELF (
    ID LONG NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL,
    ROOM VARCHAR(255),
    SHELF_LIST_ID INT NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT FK_SHELF_LIST FOREIGN KEY (SHELF_LIST_ID) REFERENCES SHELF_LIST(ID)
);

CREATE TABLE IF NOT EXISTS DRAWER (
    ID LONG NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL,
    SHELF_ID LONG,
    PRIMARY KEY (ID),
    CONSTRAINT FK_SHELF FOREIGN KEY (SHELF_ID) REFERENCES SHELF(ID)
);

CREATE TABLE IF NOT EXISTS ITEM (
    ID LONG NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL,
    DESC VARCHAR(255),
    QUANTITY int NOT NULL,
    DRAWER_ID LONG,
    PRIMARY KEY (ID),
    CONSTRAINT FK_DRAWER FOREIGN KEY (DRAWER_ID) REFERENCES DRAWER(ID)
);
